version: '3.1'

services:
  primary-db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=rentomati
    ports:
      - 3306:3306