apiVersion: "v1"
kind: "Service"
metadata:
  name: "rentomati-service"
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 9000
  selector:
    app: "rentomati"
  type: "LoadBalancer"
  loadBalancerIP: ""
